### ISSUE TITLE
Any Preview is not working

### ISSUE THREAD

**Issue by rubeldonarman** [btactic/zimbra-drive#1]
I am using Nextcloud 25 and OpenDrive v0.8.26. I can upload and download successfully. But any preview is not showing
![No Preview](https://github.com/user-attachments/assets/cf659e19-2021-4c27-960a-f5c44d9eed1f)
My Zimbra Version is 8.8.15. 
Nginx Log
103.161.x.x:31013 - - [15/Jul/2024:01:40:51 +0600]  "GET https://mail.inserver.com/service/extension/ZimbraDrive_Download/Documents/Welcome%20to%20Nextcloud%20Hub.docx?errorcallback=ZmZimbraDrivePreviewView._errorCallback&previewcallback=ZmZimbraDrivePreviewView._previewCallback&viewonly=1 HTTP/2.0" 200 354 "https://mail.server.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0" "51.195.x.x:8443" "51.195.x.x:443"

**Comment by adriangibanelbtactic** [comment]
> I am using Nextcloud 25 and OpenDrive v0.8.26. I can upload and download successfully. But any preview is not showing 

Our takeover on this project is related to the Nextcloud app, not on the Zimbra zimlet counterpart.

You can prove that this error is a consequence of the Nextcloud app by using older Nextcloud (with the old zimbra-drive app) and proving that in that *old system* you don't encounter the problem and that in the *new system* the error is found.

**Comment by adriangibanelbtactic** [comment]
I cannot seem to reproduce the error in v0.8.29 with ZCS 10.1.2.

I'll close the issue.
